In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.1'

In [4]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [5]:
df = pd.read_csv(url)

In [6]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [7]:
len(df)

9704

In [8]:
#Total number of rows and columns

df.shape

(9704, 11)

In [9]:
#Total number of rows

df.shape[0]

9704

In [10]:
#Unique fuel types

fuelTypes=df["fuel_type"].unique()

In [11]:
print(fuelTypes)

['Gasoline' 'Diesel']


In [12]:
df.isnull()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   False          False       False           False   
1                   False          False       False           False   
2                   False           True       False           False   
3                   False          False        True           False   
4                   False          False       False           False   
...                   ...            ...         ...             ...   
9699                False          False       False           False   
9700                False           True       False           False   
9701                False          False       False           False   
9702                False          False       False           False   
9703                False          False       False           False   

      acceleration  model_year  origin  fuel_type  drivetrain  num_doors  \
0            False       False   False      False       False      False   
1            False       False   False      False       False      False   
2            False       False   False      False       False      False   
3            False       False   False      False       False      False   
4            False       False   False      False       False      False   
...            ...         ...     ...        ...         ...        ...   
9699         False       False   False      False       False       True   
9700         False       False   False      False       False      False   
9701         False       False   False      False       False      False   
9702         False       False   False      False       False      False   
9703         False       False   False      False       False      False   

      fuel_efficiency_mpg  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
9699                False  
9700                False  
9701                False  
9702                False  
9703                False  

[9704 rows x 11 columns]

In [17]:
#total number of missing values overall

df.isnull().sum().sum()

np.int64(2622)

In [18]:
# Columns that have missing values

cols_with_missing = df.columns[df.isnull().any()]
print(cols_with_missing)

Index(['num_cylinders', 'horsepower', 'acceleration', 'num_doors'], dtype='object')


In [22]:
#Select cars from Asia

df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [23]:
#Calucate maximum fuel efficiency of cars from Asia

df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [25]:
# another method to calculate max fuel efficiency

max_val = df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max()
print(max_val) 

23.759122836520497


In [59]:
'''
Median value of horsepower

    1.Find the median value of horsepower column in the dataset.
    2.Next, calculate the most frequent value of the same horsepower column.
    3.Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
    4.Now, calculate the median value of horsepower once again.
'''

'\nMedian value of horsepower\n\n    1.Find the median value of horsepower column in the dataset.\n    2.Next, calculate the most frequent value of the same horsepower column.\n    3.Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.\n    4.Now, calculate the median value of horsepower once again.\n'

In [57]:
#Median value of horsepower

median_horsepower = df['horsepower'].median()
print(median_horsepower)

149.0


In [33]:
# Most frequent value

most_frequent_value = df['horsepower'].mode()[0]
print(most_frequent_value)

152.0


In [50]:
# Fill missing values in horsepower column iwth mostmost_frequent_value

df['horsepower'].isnull().sum()

np.int64(708)

In [51]:
filled_horsepwer_df = df.horsepower.fillna(most_frequent_value)

In [52]:
filled_horsepwer_df

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [53]:
filled_horsepwer_df.isnull().sum()

np.int64(0)

In [54]:
filled_median_value = filled_horsepwer_df.median()

In [55]:
print(filled_median_value)

152.0


In [58]:
'''
Sum of weights

    1.Select all the cars from Asia
    2.Select only columns vehicle_weight and model_year
    3.Select the first 7 values
    4.Get the underlying NumPy array. Let's call it X.
    5.Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    6.Invert XTX.
    7.Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
    8.Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    9.What's the sum of all the elements of the result?

'''


"\nSum of weights\n\n    1.Select all the cars from Asia\n    2.Select only columns vehicle_weight and model_year\n    3.Select the first 7 values\n    4.Get the underlying NumPy array. Let's call it X.\n    5.Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.\n    Invert XTX.\n    6.Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].\n    7.Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.\n    8.What's the sum of all the elements of the result?\n\n"

In [60]:
#Select all the cars from Asia

cars_from_asia = df[df['origin'] == 'Asia']

In [61]:
cars_from_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [62]:
#Select only columns vehicle_weight and model_year

asia_weight_year_df = df[['vehicle_weight', 'model_year']]

In [63]:
asia_weight_year_df

vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]

In [65]:
#Select the first 7 values

asia_weight_year_df.loc[0:6]

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [73]:
#Get the underlying NumPy array. Let's call it X

X = asia_weight_year_df.loc[0:6].values

In [74]:
X


array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [89]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
X_transpose = X.T
XTX= X_transpose.dot(X)

In [90]:
XTX

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [91]:
#Invert XTX

XTX_inverse = np.linalg.inv(XTX)

In [92]:
XTX_inverse

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [93]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [94]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [95]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

a= XTX_inverse.dot(X_transpose)
w = a.dot(y)

In [96]:
#What's the sum of all the elements of the result?
w.sum()

np.float64(0.4903094879707426)